### PR TITLE
Bump build to pickup noarch

### PR DESCRIPTION
**Pull request by kwilcox**

### CODE REVIEW

**Comment by kwilcox** [comment]
@conda-forge-admin, please update circle

**Comment by kwilcox** [comment]
@conda-forge-admin, please update circle

**Comment by kwilcox** [comment]
@ocefpaf @jakirkham Little help here. Merging PRs is failling with incorrect public key in circle: https://circleci.com/gh/conda-forge/scp-feedstock

Does this need to get re-added to `staged-recipes`? I thought that entire thing was long fixed.

**Comment by ocefpaf** [comment]
It may take a while for the "update circle" to work. I re-started the CI, let's see what happens.

**Comment by jakirkham** [comment]
Can use the [CircleCI command]( https://conda-forge.org/docs/webservice.html#conda-forge-admin-please-update-circle ) that @isuruf added.

**Comment by isuruf** [comment]
I forgot to add it for PR commands. It's only for issues atm. Should be easy to fix.

**Pull request merged**
